apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-uidd-tls
spec:
  secretName: k8s-uidd-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: uidesigndaily.com
  dnsNames:
    - uidesigndaily.com
    - www.uidesigndaily.com
    - blog.uidesigndaily.com
    - analytics.uidesigndaily.com
    - elastic.uidesigndaily.com
    - log.uidesigndaily.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - uidesigndaily.com
          - www.uidesigndaily.com
          - blog.uidesigndaily.com
          - analytics.uidesigndaily.com
          - elastic.uidesigndaily.com
          - log.uidesigndaily.com
